[source.crates-io]
replace-with = "ustc-sparse"

[source.ustc-sparse]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"
